[package]
name = "ip-locator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-files = "0.6.5"
actix-web = "4.6.0"
env_logger = "0.11.3"
log = "0.4.21"
reqwest = "0.12.4"
serde_json = "1.0.117"
tera = "1.19.1"
